name: socialv
description: A new Flutter project.
publish_to: 'none'

version: 8.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Common packages
  nb_utils: ^7.0.3
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.1
  lottie: ^3.1.2


  # Media
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  just_audio: ^0.9.39
  syncfusion_flutter_pdfviewer: ^26.1.41
  photo_view: ^0.15.0
  appinio_video_player: ^1.3.0
  giphy_get: ^3.5.5
  video_player: ^2.9.0
  youtube_player_flutter: ^8.1.2
  visibility_detector: ^0.4.0+2
  flutter_svg: ^2.0.10+1

  # APIs
  http: ^1.2.1
  intl: ^0.19.0
  html: ^0.15.4

  flutter_html: ^3.0.0-beta.1
  flutter_html_table: ^3.0.0-beta.2
  google_mobile_ads: ^5.1.0

  # State Management Technique
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # Share
  share_plus: ^9.0.0
  flutter_custom_tabs: ^2.1.0

  # Firebase
  firebase_crashlytics: ^4.0.3
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_messaging: ^15.0.3
  firebase_remote_config: ^5.0.3
  cloud_firestore: ^5.1.0

  #Firebase Notification
  flutter_local_notifications: ^17.2.1+1

  # AUTHENTICATION
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1


  # Story
  story_time: ^1.0.6
  numberpicker: ^2.1.2

  # Others
  flutter_emoji: ^2.5.1
  flutter_mentions: 2.0.1
  flutter_portal: ^0.4.0
  linear_timer: ^2.0.0
  country_picker: ^2.0.26
  any_link_preview: ^3.0.2
  string_contains: ^2.4.0
  modal_progress_hud_nsn: ^0.5.1

  #Payment
  flutter_stripe: ^10.2.0
  razorpay_flutter: ^1.3.7
  purchases_flutter: ^6.30.0

  # Agora
  agora_rtc_engine: ^5.2.0
  permission_handler: ^11.3.1

  flutter_localizations:
    sdk: flutter
  carousel_slider_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1
  # dart run build_runner build --delete-conflicting-outputs

dependency_overrides:

  video_player: ^2.6.0
  cached_video_player:
    git:
      url: https://github.com/vikram25897/flutter_cached_video_player
      ref: feature/gradle_version_bump


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flag/
    - assets/icons/
    - assets/lottie/

